### ISSUE TITLE
SSLConnectionSocketFactory error

### ISSUE THREAD

**Issue by dealy663** [michel-kraemer/gradle-download-task#106]
Hi,

I've been using your download plugin for almost 2 years now successfully. However I had remained at Gradle version 2.10. I'm now in the process of trying to upgrade to Gradle 4.4 and have been stuck all day on trying to figure out why I'm getting this error when using your download plugin:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.createHttpClient(DefaultHttpClientFactory.java:86)
        at de.undercouch.gradle.tasks.download.internal.CachingHttpClientFactory.createHttpClient(CachingHttpClientFactory.java:43)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:224)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:182)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:133)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:90)

Any idea of what I might be missing or doing wrong here? I'm using version 3.3.0 of your plugin. And have tried including httpclient version 4.5.4 to no avail.

Hope you can help, thanks, Derek

**Comment by michel-kraemer** [comment]
I've been using gradle-download-task 3.3.0 successfully with Gradle 4.4 for a couple of weeks now. I just added integration tests to make sure everything really works as expected (see 3e687f1ad106c7fd5f952143662e56ae5a8ec0d5).

It would be great if you could provide a minimal working build file (like [examples/simpleTask.gradle](../blob/master/examples/simpleTask.gradle)) which reproduces the error, so I can better investigate it. Thanks.

**Comment by dealy663** [comment]
My build environment is very complicated, there is a master project with many sub-projects. I took your simpleTask.gradle and dropped that in to replace one of my sub-project build.gradle files and when I ran it the first time I got this:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':HsosSdk:downloadFile'.
> INSTANCE

And then running it again I got the same errors as before about SSLConnectionSocketFactory. I guess this must mean that the problem is in either the master/build.gradle or one of its config files?

**Comment by michel-kraemer** [comment]
I'd try to disable all sub-projects and then enable them again one after the other until the error appears again. Maybe this will help to narrow down the source of the issue.

**Comment by michel-kraemer** [comment]
Have you been successful? If yes, please close the issue. If not, let me know if I can be of any more help. Thanks.

**Comment by dadoonet** [comment]
Sounds like I just hit the same issue.

I defined this task:

```
plugins {
    id "de.undercouch.download" version "3.4.2"
}

task downloadPlugins(type: Download) {
    src([
        "https://artifacts.elastic.co/downloads/elasticsearch-plugins/ingest-attachment/ingest-attachment-6.2.1.zip"
    ])
    dest project.buildDir
    overwrite false
    acceptAnyCertificate true
}
```

When I run this in the context of a submodule of https://github.com/testcontainers/testcontainers-java project, it fails with the same error but when I run it in a standalone project, it works well.

That makes me think that the parent module is bringing somehow an other version of the HttpClient lib which is incompatible here.

Just my 2 cents. But I'm not sure if this is something you can fix on your side though.

**Comment by michel-kraemer** [comment]
Thanks for the feedback. I'm also not sure if I can fix it in gradle-download-task or if it is a bug in Gradle itself. What I need is some kind of a minimal example that demonstrates the issue so I can reproduce and debug it. Without such an example, all I can do is guessing. So, if you are willing to help and somehow able to create this example, please let me know. Thanks.

**Comment by michel-kraemer** [comment]
@dealy663 @dadoonet Did you have a look at @topo75's commit? He just added ht Apache HTTP client to the build script dependencies to solve the issue:

```
runtime 'org.apache.httpcomponents:httpclient:4.5.5'
```

I don't know why this is necessary (as I said, without a minimal (not-)running example, it's impossible to debug), but maybe this also solves your problem. I'm closing this issue since it's rather old. Feel free to comment here if you have further questions or create a new issue. Thanks.

**Comment by dadoonet** [comment]
Thanks for pinging me. Sadly it's something in my TODO list and I did not get a chance to check it yet.
I'll report back here when I'll have news (good or bad) :).

**Comment by dadoonet** [comment]
So I now have:

```
plugins {
    id "de.undercouch.download" version "3.4.2"
}

description = "TestContainers :: elasticsearch"

dependencies {
    compile project(':testcontainers')
    testCompile "org.elasticsearch.client:elasticsearch-rest-client:${elasticsearchVersion}"
    runtime 'org.apache.httpcomponents:httpclient:4.5.5'
}
```

Which hopefully is correct and it is still complaining with the same error:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':elasticsearch:downloadPlugins'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.getInsecureSSLSocketFactory(DefaultHttpClientFactory.java:96)
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.createHttpClient(DefaultHttpClientFactory.java:63)
        at de.undercouch.gradle.tasks.download.internal.CachingHttpClientFactory.createHttpClient(CachingHttpClientFactory.java:43)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:246)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:204)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:156)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 32 more
```

When I have more time, I'll try to reproduce it with a sample test case.

**Comment by dadoonet** [comment]
Interesting. I updated the plugin to 3.4.3 and I'm now getting:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':elasticsearch:downloadPlugins'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:623)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:578)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.getInsecureSSLSocketFactory(DefaultHttpClientFactory.java:96)
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.createHttpClient(DefaultHttpClientFactory.java:63)
        at de.undercouch.gradle.tasks.download.internal.CachingHttpClientFactory.createHttpClient(CachingHttpClientFactory.java:43)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:247)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:205)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:157)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 32 more
```

Which is a bit different.

**Comment by michel-kraemer** [comment]
Please try adding the dependency to your `buildScript` block. So basically, instead of:

```gradle
plugins {
    id "de.undercouch.download" version "3.4.3"
}
```

You do:

```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:3.4.3'
        classpath 'org.apache.httpcomponents:httpclient:4.5.5'
    }
}

apply plugin: 'de.undercouch.download'
```

I'm really wondering which other plugin interferes with gradle-download-task here. Any insight on this would be appreciated.

I'm also wondering if the problem could be solved by creating a shadow jar and relocating the Apache HTTP client to a different package. This might introduce other problems, however. Tough call.

**Comment by chit786** [comment]
Hi .. I just started using your plugin, and stuck at 

```
Caused by: java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
        at de.undercouch.gradle.tasks.download.internal.DefaultHttpClientFactory.createHttpClient(DefaultHttpClientFactory.java:86)
        at de.undercouch.gradle.tasks.download.internal.CachingHttpClientFactory.createHttpClient(CachingHttpClientFactory.java:43)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:247)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:205)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:157)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:90)

```

I have everything in the root gradle file , also have 

  classpath 'de.undercouch:gradle-download-task:3.4.3'
        classpath 'org.apache.httpcomponents:httpclient:4.5.5'

in the dependencies but it do not seem to work.

gradle = 4.1

**Comment by dadoonet** [comment]
Do you have a gradle project file you could share?

**Comment by michel-kraemer** [comment]
@chit786 An example build file would be very helpful to reproduce the problem. As I said earlier:

> What I need is some kind of a minimal example that demonstrates the issue so I can reproduce and debug it. Without such an example, all I can do is guessing. So, if you are willing to help and somehow able to create this example, please let me know. Thanks.

Any help would be appreciated here.

**Comment by pboos** [comment]
For me it started working when I moved the following from app/build.gradle to the root build.gradle:

{project}/build.gradle
```
buildscript {
    repositories {
        ...
        jcenter()
    }
    dependencies {
        ...
        classpath 'de.undercouch:gradle-download-task:3.4.3'
        classpath 'org.apache.httpcomponents:httpclient:4.5.5'
    }
}
```

In the `{project}/app/build.gradle` I have added only the following:

```
apply plugin: 'de.undercouch.download'
...
task downloadFile(type: Download) {
    src '...'
    dest buildDir
}
preBuild.dependsOn(downloadFile)
```

**Comment by chit786** [comment]
Hi yes I was able to run it , sorry for late response as we had releases in
line . Thanks for this plugin , it’s awesome !

**Comment by dadoonet** [comment]
Awesome @pboos! This is workaround works great! 

Thanks for sharing

**Comment by michel-kraemer** [comment]
I did some refactoring and I think I finally solved the issue. If you like, you can try the latest snapshot. Use the following code to add it to your build file:

```gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'de.undercouch:gradle-download-task:4.0.0-SNAPSHOT'
    }
}

apply plugin: 'de.undercouch.download'
```

Any feedback on whether this new version works for you or not would be appreciated. Thanks.

**Comment by michel-kraemer** [comment]
By the way, explicitly adding `org.apache.httpcomponents:httpclient:4.5.5` to your build script dependencies is not necessary with the latest snapshot.
