### ISSUE TITLE
Error message missing when status code not 200.   Ensure status code is printed with exception on DownloadAction.java:635

### ISSUE THREAD

**Issue by freshcodemonger** [michel-kraemer/gradle-download-task#115]
Windows 7
Gradle 4.2

I import the sub gradle file that contains the following:

```
import de.undercouch.gradle.tasks.download.DownloadTaskPlugin
import de.undercouch.gradle.tasks.download.Download

buildscript {
  repositories {
          jcenter()
    }
    dependencies {
            classpath 'de.undercouch:gradle-download-task:3.4.3'
            classpath 'org.apache.httpcomponents:httpclient:4.5.5'
    }
}

task downloadFile(type: Download) {
    src 'https://bitbucketserver.myorg.com/rest/api/1.0/projects/MYPROJECT/repos/myrepo/browse/raw/dir1/dir2/dir3/src/main/resources/META-INF/eclipse/org.eclipse.jdt.core.prefs'
    dest '.settings'
    header 'Authorization', 'Bearer personalAuthorizationToken'
    overwrite true
    acceptAnyCertificate true
}
```

gradle -s output.

```
Exception

 is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':downloadFile'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: org.apache.http.client.ClientProtocolException:
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:142)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:762)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:729)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more
Caused by: org.apache.http.client.ClientProtocolException:
        at de.undercouch.gradle.tasks.download.DownloadAction.openConnection(DownloadAction.java:635)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:258)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:205)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:157)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:90)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 40 more
```

**Comment by freshcodemonger** [comment]
I checked your source - realized it appears I was getting a non 200 response.  I had a bad url that was returning 404 - the error message given here could be better though.

**Comment by michel-kraemer** [comment]
I cannot reproduce this. If I use your URL I get the following output:

```
java.net.UnknownHostException: bitbucketserver.myorg.com: nodename nor servname provided, or not known
```

If I use any other URL that produces a 404 (such as `http://central.maven.org/maven2/org/citationstyles/styles/1.0/styles-1.0.jar2`) I get:

```
org.apache.http.client.ClientProtocolException: Not Found
```

Everything seems to be OK. Can you provide a reproducer (a small example that demonstrates the problem)?

**Comment by freshcodemonger** [comment]
My bug report was in reference to your second example.

"ClientProtocolException: Not Found" reads to me that there is something
wrong with the protocol which when I read it means http or https was not
recognized.  Is it possible to output the http error code in addition to
the "Not Found".  If this had said "404 Not Found" I'd have found the
problem instantly.

Thank you for the plugin !  It is great !
