### ISSUE TITLE
Gradle download task fails to move file if target directory is on another disk partition

### ISSUE THREAD

**Issue by AlexanderBartash** [michel-kraemer/gradle-download-task#146]
Hello.

This code fails to move file if target directory is on another partition: https://github.com/michel-kraemer/gradle-download-task/blob/f3f6eaf6a8c70e29f0d06c440e43797e2deced98/src/main/java/de/undercouch/gradle/tasks/download/DownloadAction.java#L357
It happens because `File.renameTo` is not able to move files between partitions. See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4073756

Related to https://github.com/JetBrains/gradle-intellij-plugin/issues/457

```
Linux sasha-kubuntu 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_241 (Oracle Corporation 25.241-b07)
OS:           Linux 5.0.0-38-generic amd64
```

```
java.io.IOException: Failed to move temporary file '/media/sasha/nvme/sources/idea-plugin/build/download-task/jbr-11_0_5-linux-x64-b520.30.tar.gz568367918405127325.part' to destination file '/home/sasha/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_5-linux-x64-b520.30.tar.gz'.
        at de.undercouch.gradle.tasks.download.DownloadAction.streamAndMove(DownloadAction.java:355)
        at de.undercouch.gradle.tasks.download.DownloadAction.performDownload(DownloadAction.java:320)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:279)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:210)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:162)
```

Permissions on the folders look good:
```
sasha@sasha-kubuntu:~ $ ll ~/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/
total 8.0K
drwxrwxr-x 2 sasha sasha 4.0K Jan 25 21:14 .
drwxrwxr-x 3 sasha sasha 4.0K Jan 25 21:14 ..

sasha@sasha-kubuntu:~ $ ll ~/sources/idea-plugin/build/download-task/
total 258M
drwxrwxr-x  2 sasha sasha 4.0K Jan 25 21:16 .
drwxrwxr-x 11 sasha sasha 4.0K Jan 25 21:15 ..
-rw-rw-r--  1 sasha sasha 106M Jan 25 21:16 jbr-11_0_5-linux-x64-b520.30.tar.gz3826401119714448048.part
-rw-rw-r--  1 sasha sasha  46M Jan 25 21:16 jbr-11_0_5-linux-x64-b520.30.tar.gz5393996891986106795.part
-rw-rw-r--  1 sasha sasha 106M Jan 25 21:15 jbr-11_0_5-linux-x64-b520.30.tar.gz7231496779691058520.part
```

In fact if I try to move it manually it works and on the next run Gradle plugin is not trying to download JBR again.
```
mv /media/sasha/nvme/sources/idea-plugin/build/download-task/jbr-11_0_5-linux-x64-b520.30.tar.gz568367918405127325.part /home/sasha/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_5-linux-x64-b520.30.tar.gz
```

**Comment by AlexanderBartash** [comment]
I think it might be related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4073756

```
Rather than throwing an exception, the File.renameTo method returns a boolean
to indicate success or failure; the submitted code does not check this value.

In this case the renameTo method is failing because, unlike the Unix "mv"
command, the File.renameTo method is not specified to copy a file across
filesystems when necessary; it will only rename a file within a single
filesystem.
```

In my case it istrying to move file from one physical disk to another. It means `File.renameTo` is bad API for this. It would be better to use something else what can move file between disks.

**Comment by AlexanderBartash** [comment]
Yes. I've tried to move my project into the same partition as the target directory and it works now. I will modify description of this ticket to better reflect the situation.

**Comment by michel-kraemer** [comment]
Thanks for the thorough analysis. I will try to fix this as soon as possible.

**Comment by michel-kraemer** [comment]
OK. I fixed the issue. Do you want me to release a new version?

**Comment by AlexanderBartash** [comment]
@michel-kraemer Hi. Thank you for the quick fix :) If you can release it soon it would be great. I would talk to maintainers of Intellij Gradle plugin about updating the dependency. But it is not very urgent because in my case it is possible to workaround by manually copying file or moving project. But I guess other Gradle projects might be using your libs and they would benefit from a release as well.

Thank you!

**Comment by michel-kraemer** [comment]
The new version 4.0.4 is now available.

**Comment by AlexanderBartash** [comment]
Thank you very much!

**Comment by AlexanderBartash** [comment]
Hi. I have updated the dependency and it works now. Thank you!
