### ISSUE TITLE
Download fails if source URL contains a question mark

### ISSUE THREAD

**Issue by clo-vis** [michel-kraemer/gradle-download-task#151]
(Windows 10; de.undercouch.download 4.0.4; Gradle 6.1.1)

```
task downloadFile(type: Download) {
    src 'https://routenplaner.verkehrsauskunft.at/vao/restproxy/v1.0.0/xsd?rest-1.28.xsd'
    dest buildDir
}
```
> gradlew downloadFile

```
* What went wrong:
Execution failed for task ':downloadFile'.
> java.io.IOException: Bad pathname

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':downloadFile'.
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:244)
…
Caused by: java.io.IOException: Bad pathname
        at org.gradle.execution.plan.LocalTaskNode.canonicalizePath(LocalTaskNode.java:274)
        ... 123 more
```

**Comment by michel-kraemer** [comment]
This is an issue with Windows and not with the plugin. You can set a fixed file name like so:

    dest "$buildDir/rest-1.28.xsd"
