### ISSUE TITLE
Increased socket read timeouts with 4.0.4

### ISSUE THREAD

**Issue by jrodbx** [michel-kraemer/gradle-download-task#152]
CashApp migrated from 3.4.3 to 4.0.4 since we were seeing the following:

```
> Task :protos:downloadProtos
Unable to get progress logger. Download progress will not be displayed.
```

However, we're seeing a lot more socket read connection timeouts with 4.x to the point where it's unusable.  I noticed the 4.0.1 release was deliberately published to fix some regressions in this area.  My guess is there may be more regressions.  I'm happy to help provide feedback to nail down the root cause.

Error message:

```
Caused by: java.net.SocketTimeoutException: Read timed out
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at de.undercouch.gradle.tasks.download.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at de.undercouch.gradle.tasks.download.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at de.undercouch.gradle.tasks.download.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at de.undercouch.gradle.tasks.download.DownloadAction.openConnection(DownloadAction.java:647)
        at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:266)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:213)
        at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:165)
        at de.undercouch.gradle.tasks.download.Download.download(Download.java:88)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Comment by jrodbx** [comment]
Hmm, thinking it might be related to this: https://github.com/michel-kraemer/gradle-download-task/commit/712cfedb91ccbf9728a7a42f13fcad3b0ba0e509#diff-bebb9d8bb562195e97c2e6e9ed82981f

**Comment by jrodbx** [comment]
Yep, setting `readTimeout 0` to locally revert from 30s back to infinite resolves this issue!
