### ISSUE TITLE
Could not create task of type 'Download' on 5.x

### ISSUE THREAD

**Issue by ahamana** [michel-kraemer/gradle-download-task#189]
I encounter the following exception after upgrading from 4.x to 5.x.
Does the "org.apache.httpcomponents.client5:httpclient5" need to be add to dependencies?

## Task
```
tasks.register('schemaSpyDownload', Download) {
    description = 'Downloads SchemaSpy File.'

    ext.schemaSpyFile = layout.projectDirectory.file("${downloadTaskDir}/SchemaSpy/schemaspy.jar").asFile

    src('https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar')
    dest(schemaSpyFile)
    overwrite(false)
}
```

## StackTrace
> Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'Download'.
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:95)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:82)
        at org.gradle.util.internal.GUtil.uncheckedCall(GUtil.java:458)
        at org.gradle.api.internal.AbstractTask.injectIntoNewInstance(AbstractTask.java:216)
        at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:82)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:48)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:322)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:76)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:697)
        at org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreatingProvider.createDomainObject(DefaultTaskContainer.java:654)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:941)
        ... 211 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hc/client5/http/auth/Credentials
        at de.undercouch.gradle.tasks.download.Download.<init>(Download.java:50)
        at de.undercouch.gradle.tasks.download.Download_Decorated.<init>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2078)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:488)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:50)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:88)
        ... 221 more
Caused by: java.lang.ClassNotFoundException: org.apache.hc.client5.http.auth.Credentials
        ... 231 more

**Comment by michel-kraemer** [comment]
Normally not. Let me check ...

**Comment by michel-kraemer** [comment]
It seems the plugin was not correctly published to the Gradle plugin portal. Let me try to fix that ...

**Comment by michel-kraemer** [comment]
I've fixed version 5.0.0 in the plugin portal but, to be on safe side, I also released 5.0.1. Both versions should work now. Please try again. I'm sorry for the inconvenience.

**Comment by BorzdeG** [comment]
After updating the plugin to version 5.0.1, the error disappeared on my project.

**Comment by ahamana** [comment]
@michel-kraemer 
Many thanks for fixing the issue quickly.

**Comment by michel-kraemer** [comment]
My pleasure. Thanks for the feedback, @BorzdeG and @ahamana!
