### ISSUE TITLE
Change in Gradle 2.6 breaks download task

### ISSUE THREAD

**Issue by bgorven** [michel-kraemer/gradle-download-task#29]
Hi, I just tried updating to gradle 2.6, and I get this exception:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':download'.
	at (snip)
Caused by: java.lang.NoSuchMethodError: org.gradle.logging.ProgressLogger.setDescription(Ljava/lang/String;)V
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:139)
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:88)
	at de.undercouch.gradle.tasks.download.Download.download(Download.java:45)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
```

It may be related to this change: https://github.com/gradle/gradle/commit/9f04302ad34bd805208c7d51a2b7583f84c08777#diff-f3941464cb83476ea37bc67c9da36883L55

It's not an immediate problem, I just downgraded back to gradle 2.5 for now, but I thought I would let you know.

**Comment by michel-kraemer** [comment]
Thanks a lot. Should be easy to fix. I'll see what I can do and get back to you.

Cheers,
Michel

**Comment by bgorven** [comment]
Thanks, I'll keep an eye out.

**Comment by mgoellnitz** [comment]
It seems to me as if a simple re-compile with API Level 2.6 will fix this:

```Java
group = 'de.undercouch'
version = '1.3'
sourceCompatibility = '1.7'
targetCompatibility = '1.7'

idea {
  project {
    languageLevel = '1.7'
    ipr {
      withXml { provider ->
        provider.node.component
          .find { it.@name == 'VcsDirectoryMappings' }
          .mapping.@vcs = 'Git'
      }
    }
  }
}


dependencies {
    compile gradleApi()
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.6'
}
```

(build.gradle - of course)

Just created a patched version and it did a successful download.

**Comment by michel-kraemer** [comment]
@mgoellnitz Thanks for the hint. Unfortunately this broke compatibility with previous Gradle versions. The commit I just pushed fixes this.

**Comment by michel-kraemer** [comment]
@bgorven @mgoellnitz I'll release a new version tomorrow. If you like to test the plugin before then feel free to do so. I would be glad to hear if it works for you.

**Comment by bgorven** [comment]
Just updated to download-task 2.0.0, worked flawlessly for gradle 2.5 and 2.6. Thanks!

Sorry I didn't get a chance to test it before.
