### ISSUE TITLE
SSLPeerUnverifiedException jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com

### ISSUE THREAD

**Issue by androideveloper** [michel-kraemer/gradle-download-task#317]
In our project we use `react-native-reanimated`, which has implementation of [downloadBoost](https://github.com/software-mansion/react-native-reanimated/blob/278f5ba60978d0da11ff162aa7b92f55deeca7d9/android/build.gradle#L757) method. Under the hood, that method uses this library to download a specific version of the boost.

We also use kotlin-gradle-plugin v1.7.10 in our `buildSrc` scripts and currently trying to bump that to [1.7.20](https://github.com/JetBrains/kotlin/releases/tag/v1.7.20)+.  With the new bump, we get this exception when downloading of the boost file happens:
```
A failure occurred while executing de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction
   > javax.net.ssl.SSLPeerUnverifiedException: Certificate for <jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]
```

Not sure what could cause this with the Kotlin bump. Would you be able to help with checking this?

Full exception
```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.DefaultHostnameVerifier.matchDNSName(DefaultHostnameVerifier.java:165)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:120)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.TlsSessionValidator.verifySession(TlsSessionValidator.java:112)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.verifySession(SSLConnectionSocketFactory.java:311)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:300)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:274)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:241)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)	
at de.undercouch.gradle.tasks.download.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)	
at de.undercouch.gradle.tasks.download.DownloadAction.openConnection(DownloadAction.java:761)	
at de.undercouch.gradle.tasks.download.DownloadAction.executeHttpProtocol(DownloadAction.java:341)	
at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:287)	
at de.undercouch.gradle.tasks.download.DownloadAction.lambda$execute$0(DownloadAction.java:227)	
at de.undercouch.gradle.tasks.download.internal.DefaultWorkerExecutorHelper$DefaultWorkAction.execute(DefaultWorkerExecutorHelper.java:72)
```

**Comment by androideveloper** [comment]
Workarounds:
- downgrade gradle-download-task to 4.1.2 (current version we use 5.0.1)
- adding `acceptAnyCertificate(true)` to the downloadBoost method

this issue looks similar to https://github.com/michel-kraemer/gradle-download-task/issues/56

**Comment by michel-kraemer** [comment]
May I ask you to provide a small reproducer build script? Otherwise, it will be really hard to debug what's the issue here. Thanks.

**Comment by androideveloper** [comment]
Hey Michel! Looks like it's fixed now after bumping RN to the 0.71. Thanks!

**Comment by frett** [comment]
I just ran into this bug when migrating our custom download logic from being defined in `buildSrc` over to a composite build.

I was able to hook up a debugger to the problematic gradle task both before and after the migration and found that the `PublicSuffixMatcherLoader` from httpclient was loading the PSL (`PublicSuffixMatcherLoader.class.getResource("/mozilla/public-suffix-list.txt")`) from different jar files. When the download task worked successfully it loaded the PSL from the `gradle-download-task-5.4.0.jar` file, when the download task had the SSLVerifierException, it was loading the PSL from `kotlin-gradle-plugin-1.9.0.jar`.

it looks like `kotlin-gradle-plugin-1.9.0.jar` still bundles version `gradle-download-task-4.1.1.jar` which includes the outdated list.  The format of the `s3.amazonaws.com` entry in the PSL changed between the 2 files, which is what is leading to the verification error, in the older list it was included as `*.s3.amazonaws.com`, in the newer list it has been changed to `s3.amazonaws.com`

This would seem to indicate that this bug would be flaky depending on the order of dependencies in the classpath. I'm not sure of a workaround to fix this without just disabling certificate hostname verification completely.

**Comment by frett** [comment]
a workaround that appears to have worked for me is loading the gradle-download-task dependency on the classpath before loading the kotlin gradle plugin, this is causing `PublicSuffixMatcherLoader` to load the correct `public-suffix-list.txt`

**Comment by michel-kraemer** [comment]
@frett Thanks for the thorough analysis. I've relocated the public suffix list so this issue won't happen again. I will release 5.5.0 later today, which will include the fix. Of course, in case of kotlin-gradle-plugin, this requires that gradle-download-task is also up to date. I will file an issue in their repository.
