### ISSUE TITLE
download seems to be broken again wrt progresslogger for gradle 2.7.

### ISSUE THREAD

**Issue by mrampson** [michel-kraemer/gradle-download-task#32]
Maybe we should just not use progresslogger any more and use logger lifecycle or some such instead.  Works if you run with --quiet as it skips this code block.

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':prepareAnalytics'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoSuchMethodError: org.gradle.logging.ProgressLogger.setDescription(Ljava/lang/String;)V
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:139)
	at de.undercouch.gradle.tasks.download.DownloadAction.execute(DownloadAction.java:88)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:44)
	at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:29)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at analytics_4y63yhsnzsqc3hu3cs2amygbb$_run_closure2.doCall(/Users/.../projects/.../build/gradle/task/browser_tests/analytics.gradle:24)
```

**Comment by michel-kraemer** [comment]
Thanks for reporting. The latest commit on master adds an integration test for 2.7 that runs fine. I didn't release a new version because I thought everything was OK. Can you post a small reproducer for this issue?

Michel

**Comment by michel-kraemer** [comment]
Oh and by the way, I'm using gradle-download-task 2.0 with gradle 2.7 here:
https://github.com/michel-kraemer/vertx-lang-typescript

It works quite well.

Michel

**Comment by mrampson** [comment]
Yeah, go ahead and close it.  It was dying in a module where it was expressly grabbing 1.1 instead of the 2.0.0 I was using globally.  Sorry for the false alarm.
